### ISSUE TITLE
weird histogram display

### ISSUE THREAD

**Issue by baligoyem** [parrt/dtreeviz#196] opened 2022-09-27 11:28 UTC
Hi again,

After modeling when I draw trees, I always get the histogram of "U" variable as below:

![image](https://user-images.githubusercontent.com/61024126/192492818-8aea1d72-836d-43fa-aeda-34409c18e264.png)

It's not clear to interpret and I don't know why it seems like that. I don't think it's due to data. Because, I tried changing the name of this variable or divided the values by 10, but nothing has changed after that.

I am sharing the data and my brief notebook below. So you can read data and run codes in your local and see the issue in trees. As I was saying previously, the weird display happens to the "U" variable only.

```
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import lightgbm as lgb
from sklearn.metrics import f1_score
import optuna
from dtreeviz.trees import dtreeviz 
from dtreeviz.models.lightgbm_decision_tree import ShadowLightGBMTree
#Supress optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)
import logging
logging.getLogger('matplotlib.font_manager').disabled = True
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 300)

df_code_tree = pd.read_excel('df_code_tree.xlsx')

# ### Modeling


X_tree=df_code_tree.drop('TARGET', axis=1)
y_tree=df_code_tree.TARGET

#split data into training and test sets
X_train_tree, X_test_tree, y_train_tree, y_test_tree = train_test_split(X_tree, y_tree, test_size = 0.30, random_state=42)

if y_train_tree.value_counts()[0] < 9*y_train_tree.value_counts()[1]:
    pass
else:
    # instantiating over and under sampler
    over = RandomOverSampler(sampling_strategy=0.33)
    under = RandomUnderSampler(sampling_strategy=0.5)
    # first performing oversampling to minority class
    X_train_tree, y_train_tree = over.fit_resample(X_train_tree, y_train_tree)
    # now to combine under sampling 
    X_train_tree, y_train_tree = under.fit_resample(X_train_tree, y_train_tree)

#DT oluştururken 'class_names' ataması yapmak için hedef değişken içeriğini (0,1) olarak bir listede tutuyor ve isimlendiriyoruz.
target = sorted(y_train_tree.unique())

target[0] = "0"
target[1] = "1"

y_train_tree = y_train_tree.astype('int')
y_test_tree = y_test_tree.astype('int')

def objective(trial, train_x, train_y, test_x, test_y):
    dtrain = lgb.Dataset(train_x, label=train_y)
 
    param = {
        "objective":"binary",
        "random_state":42,
        "force_col_wise":True,
        "verbose":-1,
        "n_estimators": trial.suggest_categorical("n_estimators", [10,15,25]),
        "learning_rate": trial.suggest_categorical("learning_rate", [0.003,0.01,0.02,0.15,0.3]),
        "colsample_bytree": trial.suggest_categorical("colsample_bytree", [0.5,0.6,0.8,0.9,1.0]),
        "num_leaves": trial.suggest_int("num_leaves", 8, 64),
        "max_depth": trial.suggest_int("max_depth", 3, 7),
        "min_child_samples": trial.suggest_categorical("min_child_samples", [13,15,19]),
        "reg_alpha": trial.suggest_loguniform("reg_alpha", 1e-3, 10.0),
        "reg_lambda": trial.suggest_loguniform("reg_lambda", 1e-3, 10.0),
        "min_split_gain": trial.suggest_categorical("min_split_gain", [0.0005,0.001,0.0015,0.002])
    }
 
    gbm = lgb.train(param, dtrain)
    preds = gbm.predict(test_x)
    pred_labels = np.rint(preds)
    f1 = f1_score(test_y, pred_labels)
    return f1
 
study = optuna.create_study(sampler=optuna.samplers.RandomSampler(seed=42), direction="maximize", study_name="LGBM Classifier")
func = lambda trial: objective(trial, X_train_tree, y_train_tree, X_test_tree, y_test_tree)
study.optimize(func, n_trials=1000)

#print(f"\tBest value (f1_score): {study.best_value:.5f}")
#print(f"\tBest params:")

#for key, value in study.best_params.items():
 #   print(f"\t\t{key}: {value}")
    
params = study.best_params
params['objective']='binary'
params['random_state']=42
params['verbose']=-1
params['force_col_wise']=True
params['n_jobs']=-1
gbm_dtreeviz = lgb.train(params, lgb.Dataset(X_train_tree, label=y_train_tree))

light_dtree = ShadowLightGBMTree(gbm_dtreeviz, tree_index=0, x_data=X_train_tree, y_data=y_train_tree, feature_names=list(X_tree), target_name="quality_status", class_names=target)
dtreeviz(light_dtree, scale=1.75)
```

[df_code_tree.xlsx](https://github.com/parrt/dtreeviz/files/9653155/df_code_tree.xlsx)

**Comment by parrt** [comment] 2022-10-09 20:50
wow! Now that is weird.

**Comment by tlapusan** [comment] 2022-10-10 12:03
thanks @baligoyem for creating this issue and putting the code and data to reproduce it. Indeed, it's weird. 
I will take a look on it now.

**Comment by tlapusan** [comment] 2022-10-10 12:41
good thing is that I succeeded to reproduce the issue after some install libraries issues.

**Comment by parrt** [comment] 2022-10-10 18:56
Awesome. Mystifying but it must be some weird artifact of the data range or something.

**Comment by baligoyem** [comment] 2022-10-10 20:50
I have been using this package for more than a half year. During this period, data has grown, however the weird histogram of "U" has never changed in any trees :D

**Comment by tlapusan** [comment] 2022-10-11 07:24
Yes, first I thought it's about data range for the U feature, but it shouldn't be.
This is the feature value distributions : 
<img width="1132" alt="Screenshot 2022-10-11 at 10 22 40" src="https://user-images.githubusercontent.com/12815158/195022400-24d964df-6b2f-4684-ad98-bd33bd0fb5ec.png">

The issue is somewhere we define the set_xlim... but don't understand yet why 
`ax.set_xlim(*overall_feature_range_wide)`

if I change this like to ax.set_xlim(auto=True) for the U node it looks fine.
<img width="1223" alt="Screenshot 2022-10-11 at 10 21 00" src="https://user-images.githubusercontent.com/12815158/195022688-fd5fb0c1-9386-4363-98a3-8ae3f8a52e89.png">

I will further investigate

**Comment by parrt** [comment] 2022-10-13 17:06
Thanks, @tlapusan  Yeah, I said the xlim for a specific reason but I can't remember the details now :(

**Comment by tlapusan** [comment] 2022-10-15 11:23
yeah, I think it's a xlim and value distribution issue... we can see that the feature O has kind of the same issue.

**Comment by tlapusan** [comment] 2022-10-15 13:09
@parrt 
I have an explanation:
1. the range of values for feature U for a node is 8381.333333333334, 8442.0
2. because we want to have some blank space on left/right of oX axe, we calculate the overall_feature_range_wide with this formula

**Comment by tlapusan** [comment] 2022-10-23 11:37
@parrt any feedback on this ?

I want to make soon a PR with this, because I think that using the bin length as left/right blank spaces is even better. 

Using the dataset sent my @baligoyem we can see that there are issues not only for feature U(which is the most obvious), but also for feature O, where the bins are narrower compared with the others.

**Comment by parrt** [comment] 2022-10-23 18:24
hi! Yes, I really want to keep the width of the bins to be the same and that is not true even in the original as you point out. I think we'd have to view this against all of our examples to see what happened with your change. Seems like we need to figure out what value is going into set_xlim and why it is so wide, causing the histogram to be so narrow. (sorry I'm distracted by a bunch of ANTLR-related issues.)

**Comment by tlapusan** [comment] 2022-10-23 18:47
@parrt I posted an explanation few comments ago about why the histogram is so narrow. 
In a nutshell, the interval for that feature U is between [8381, 8442]. Based on the current formula to calculate the x_lim values, we have the interval [7710, 8864].
From the feature range values, [8381, 8442], we calculate 20 bins intervals with length aprox 3 each. This length 3 is very very small compared with the x_lim interval [7710, 8864] => very very narrow bins.

From my poor math, this will happen any times when the feature have large values, but its value range is pretty small :))

**Comment by parrt** [comment] 2022-10-23 19:40
Something is strange here because the xlim should be bracketing it just wider than the range of values. Ugh. My brain is stuck and something else at the moment so you're only getting about 15% CPU at this moment haha.

**Comment by tlapusan** [comment] 2022-10-23 19:50
It's easier when you put it on paper :)) it worked for me at least.

**Comment by tlapusan** [comment] 2022-11-27 08:37
@baligoyem this PR should resolve the issue. Thanks for raising the issue ;)
https://github.com/parrt/dtreeviz/pull/201.

**Comment by baligoyem** [comment] 2022-11-27 10:28
Thanks for your efforts and this amazing library :) It is really helpful for interpreting and explaining decision trees to the end users who are non-technical. 

Is the only thing I should do updating the library to get this change, right?

**Comment by tlapusan** [comment] 2022-11-27 17:46
@baligoyem thank you for the kind words.
First the PR should be merged and @parrt can make a new release. Only after new release you could update the library to get the changes :)

Do you have some use cases where you find useful the library ? It would help us to better understand how people are using it. Thanks1

**Closed** 2022-11-27 22:36 UTC
Labels: bug

**Comment by parrt** [comment] 2022-11-27 22:39
Ok, @baligoyem please give it a shot!  1.4.1 version.
