### ISSUE TITLE
TypeError: unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by grilhami** [parrt/dtreeviz#32] opened 2019-01-27 19:08 UTC
I am having an issue with visualizing decision trees with `dtreeviz`. I am running this on Ubuntu 18.04 using an anaconda environment using Python 3.6.0 and Jupyter Notebook.

I used the following example with some changes.

```
regr = tree.DecisionTreeRegressor(max_depth=2)
boston = load_boston()
regr.fit(boston.data, boston.target)

viz = dtreeviz(regr,
               boston.data,
               boston.target,
               target_name='price',
               feature_names=boston.feature_names)
              
viz.view()              

```
I tried to use the same code on my nutrient database.

```
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import export_graphviz

dtree = DecisionTreeRegressor()
dtree.fit(tree_X, tree_y)

from dtreeviz.trees import dtreeviz

viz = dtreeviz(dtree,
               tree_X,
               tree_y,
               target_name='Iron_(mg)',
               feature_names=['Fiber_TD_(g)', 'Carbohydrt_(g)'])
              
viz.view()  
```
It returned the following error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-82-60a9d000cb22> in <module>
      5                tree_y,
      6                target_name='Iron',
----> 7                feature_names=np.array(['Fiber_TD_(g)', 'Carbohydrt_(g)'], dtype='<U17'))
      8 
      9 viz.view()

~/anaconda3/envs/playground/lib/python3.6/site-packages/dtreeviz/trees.py in dtreeviz(tree_model, X_train, y_train, feature_names, target_name, class_names, precision, orientation, show_root_edge_labels, show_node_labels, fancy, histtype, highlight_path, X, max_X_features_LR, max_X_features_TD)
    672 
    673     shadow_tree = ShadowDecTree(tree_model, X_train, y_train,
--> 674                                 feature_names=feature_names, class_names=class_names)
    675 
    676     if X is not None:

~/anaconda3/envs/playground/lib/python3.6/site-packages/dtreeviz/shadow.py in __init__(self, tree_model, X_train, y_train, feature_names, class_names)
     68         self.unique_target_values = np.unique(y_train)
     69         self.node_to_samples = ShadowDecTree.node_samples(tree_model, X_train)
---> 70         self.class_weights = compute_class_weight(tree_model.class_weight, self.unique_target_values, self.y_train)
     71 
     72         tree = tree_model.tree_

~/anaconda3/envs/playground/lib/python3.6/site-packages/sklearn/utils/class_weight.py in compute_class_weight(class_weight, classes, y)
     39     from ..preprocessing import LabelEncoder
     40 
---> 41     if set(y) - set(classes):
     42         raise ValueError("classes should include all valid labels that can "
     43                          "be in y")

TypeError: unhashable type: 'numpy.ndarray'
```
I thought it's because it wanted me to out in a numpy array type instead of a list. But after checking out `dtreeviz` in my notebook, it required a list for the argument.

But I tried it anyway by converting the list to a numpy array.

```
viz = dtreeviz(dtree,
               tree_X,
               tree_y,
               target_name='Iron_(mg)',
               feature_names=np.array(['Fiber_TD_(g)', 'Carbohydrt_(g)']))
              
viz.view()  
```
But I still got the same error.

Then I tried to match the datatype the same as the boston datastet features name.

```
from sklearn.datasets import load_boston
boston = load_boston()
boston.feature_names

# Output
array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'],
      dtype='<U7')
```

```
viz = dtreeviz(dtree,
               tree_X,
               tree_y,
               target_name='Iron_(mg)',
               feature_names=np.array(['Fiber_TD_(g)', 'Carbohydrt_(g)'], dtype='<U7'))
              
viz.view()
```

But I still got the same error every time. I'm not really sure what happened. I was wondering if there was something I was missing?

**Comment by parrt** [comment] 2019-01-27 19:16
it wants a list not an array for sure, but not sure why your list doesn't work. what type is `boston.feature_names`?

**Comment by parrt** [comment] 2019-02-01 20:33
@grilhami Hmm...it can't be the features as this works:

```
>>> import numpy as np
>>> np.array(['a','b','c'])
array(['a', 'b', 'c'], dtype='<U1')
>>> x = np.array(['a','b','c'])
>>> set(x)
{'a', 'c', 'b'}
>>> 
```

It must be the class weights passed to the tree model. can you print `regr.class_weight` for me?

**Comment by JSAN730** [comment] 2019-04-07 00:31
I'm getting the same issue... has this been fixed?

**Comment by JSAN730** [comment] 2019-04-07 00:32
regr.class_weight is none for me

**Comment by parrt** [comment] 2019-04-07 15:52
@JSAN730 are you using 0.3.3 dtreeviz?

**Comment by JSAN730** [comment] 2019-04-07 16:00
Yup, I'm using 0.3.3 dtree viz

**Comment by parrt** [comment] 2019-04-07 16:03
Damn. ok, if you send me a small test.py and a sample dataset (or pull from sklearn), I'll track it down

**Comment by JSAN730** [comment] 2019-04-07 16:08
I was assuming that feature_names was just a list of the column names for the data with predictor variables. I'll send you the test.py and sample dataset. Below is my code:

features = list(vf_ulta_per_data)

viz = dtreeviz(regr,
               vf_ulta_per_data,
               vf_ulta_per_target,
               target_name= 'VF % ULTA 2018',  # this name will be displayed at the leaf node
               feature_names=features
              )
viz

**Comment by parrt** [comment] 2019-04-07 16:09
Hmm...yeah, that should work. let's figure this out. you can email me at parrt@cs.usfca.edu

**Comment by parrt** [comment] 2019-04-07 16:24
I'm getting a different error than was reported.  Is this what you see @JSAN730 ?

```
ValueError                                Traceback (most recent call last)
<ipython-input-1-c47ac4c24103> in <module>
     27                vf_ulta_per_target,
     28                target_name= 'VF % ULTA 2018',  # this name will be displayed at the leaf node
---> 29                feature_names=features
     30               )
     31 viz

~/anaconda3/lib/python3.7/site-packages/dtreeviz-0.3.2-py3.7.egg/dtreeviz/trees.py in dtreeviz(tree_model, X_train, y_train, feature_names, target_name, class_names, precision, orientation, show_root_edge_labels, show_node_labels, fancy, histtype, highlight_path, X, max_X_features_LR, max_X_features_TD)
    681 
    682     shadow_tree = ShadowDecTree(tree_model, X_train, y_train,
--> 683                                 feature_names=feature_names, class_names=class_names)
    684 
    685     if X is not None:

~/anaconda3/lib/python3.7/site-packages/dtreeviz-0.3.2-py3.7.egg/dtreeviz/shadow.py in __init__(self, tree_model, X_train, y_train, feature_names, class_names)
     68         self.unique_target_values = np.unique(y_train)
     69         self.node_to_samples = ShadowDecTree.node_samples(tree_model, X_train)
---> 70         self.class_weights = compute_class_weight(tree_model.class_weight, self.unique_target_values, self.y_train)
     71 
     72         tree = tree_model.tree_

~/anaconda3/lib/python3.7/site-packages/sklearn/utils/class_weight.py in compute_class_weight(class_weight, classes, y)
     40 
     41     if set(y) - set(classes):
---> 42         raise ValueError("classes should include all valid labels that can "
     43                          "be in y")
     44     if class_weight is None or len(class_weight) == 0:

ValueError: classes should include all valid labels that can be in y
```

**Comment by JSAN730** [comment] 2019-04-07 16:25
Yes, I'm getting that same message.

ValueError: classes should include all valid labels that can be in y

**Comment by parrt** [comment] 2019-04-07 16:26
ah. well, isn't that supposed to be same?

<img width="352" alt="Screen Shot 2019-04-07 at 9 26 09 AM" src="https://user-images.githubusercontent.com/178777/55686522-3b912a80-5917-11e9-9bcf-8a95caa69517.png">

**Comment by JSAN730** [comment] 2019-04-07 16:31
how should I code it if the target is a continuous variable (like sales) and I'm using the other columns in the dataset to create a regression tree as predictor variables?

**Comment by parrt** [comment] 2019-04-07 16:32
if continuous, then it's regression so you can't use class_weights.  Maybe you want sample_weights?

**Comment by JSAN730** [comment] 2019-04-07 16:37
That's correct, I'm trying to run a regression tree. I'm new to python, I'll try to find where I can replace class_weights to sample_weights. I thought the tree.DecisionTreeRegressor() took care of that.

**Comment by parrt** [comment] 2019-04-07 16:38
The term "class" is meant for classifiers so that arg is definitely not the one you want. :)

**Comment by lucas817** [comment] 2019-04-12 13:11
I'm having the same issue (ValueError: classes should include all valid labels that can be in y). I don't fully understand the previous discussion: is this a bug that will be fixed, or is there a way to make the function not try to use class weights on a regression tree? Because as it is the only regression trees that can be visualised are the ones from built-in datasets like the boston one, which would be a shame.

**Comment by parrt** [comment] 2019-04-12 18:11
I wonder if you are mixing up regression versus classifier. Classifiers are the only ones that need to pass in the target class names. There are no such things for a regressor, which predicts a numeric value.

**Comment by lucas817** [comment] 2019-04-12 18:19
I know what the difference between regression and classification is, I'm a statistician. My point is that the error appears every time, whether you pass a regression model or a classifier, it makes no difference. The only way I've gotten this to work is with built in datasets like iris and boston. Is this package only meant to be used with those or can it also be used with pandas dataframes (and if so, how)?

**Comment by parrt** [comment] 2019-04-12 18:21
oh! Sorry. I've used on all sorts of datasets. Can you send me a failing example? I'll track it down! parrt@cs.usfca.edu   It must be a weird data type issue with the list of feature names.

**Comment by JSAN730** [comment] 2019-04-12 18:56
@lucas817 

for me, I changed the target dataset a numpy array and it worked
penetrationtarget = np.array(penetrationbeddf_c['vf_penetration'])

**Comment by parrt** [comment] 2019-04-12 19:06
oh! yeah, it has to be a dataframe series or a numpy array I think. what type are you passing in? i can update.

**Comment by parrt** [comment] 2019-05-26 19:38
Ok, i *think* this was because `compute_class_weight()` was called even for regressors, but it only makes sense for classifiers. **ALSO**, it sounds like maybe your `tree_y` was not a simple 1D array but maybe 2D.

**Closed** 2019-05-26 19:38 UTC
Labels: bug
