### ISSUE TITLE
Path problems

### ISSUE THREAD

**Issue by nmandic78** [parrt/dtreeviz#109] opened 2020-10-04 12:09 UTC
On windows 10, graphviz, dtreeviz installed, dot is here, env variables set, but getting error with view and save functions.

**Trying unmodified sample (https://github.com/parrt/dtreeviz/blob/master/testing/iris.py), I get error:** 
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tsvg', '-o', '/tmp/t.svg', '/tmp\\t'], make sure the Graphviz executables are on your systems' PATH
on: viz_iris().save("/tmp/t.svg")

**Another example (here on view method):**
failed to execute ['dot', '-Tsvg', '-o', 'C:\\Users\\user\\AppData\\Local\\Temp\\DTreeViz_4516.svg', 'C:/Users/user/AppData/Local/Temp\\DTreeViz_4516'], make sure the Graphviz executables are on your systems' PATH
Should it be able to handle this: "/Temp\\DTreeViz_4516"?

I don't think it can't find dot, but maybe has problems with converting different path formats. Any advice what could I try?

**Installed packages and dot -V:**
C:\Users\\source\repos\AdaBoost_testing_1a\DecisionTreeVisualization_1a>pip show graphviz
Name: graphviz
Version: 0.14.1
Summary: Simple Python interface for Graphviz
Home-page: https://github.com/xflr6/graphviz
Author: Sebastian Bank
Author-email: sebastian.bank@uni-leipzig.de
License: MIT
Location: d:\apps\anaconda3\lib\site-packages
Requires:
Required-by: dtreeviz

C:\Users\\source\repos\AdaBoost_testing_1a\DecisionTreeVisualization_1a>pip show dtreeviz
Name: dtreeviz
Version: 1.1.2
Summary: A Python 3 library for sci-kit learn and XGBoost decision tree visualization
Home-page: https://github.com/parrt/dtreeviz
Author: Terence Parr, Tudor Lapusan, and Prince Grover
Author-email: parrt@cs.usfca.edu
License: MIT
Location: d:\apps\anaconda3\lib\site-packages
Requires: graphviz, scikit-learn, pandas, pytest, numpy, xgboost, matplotlib, colour, pyspark
Required-by:

C:\Users\\source\repos\AdaBoost_testing_1a\DecisionTreeVisualization_1a>dot -V
dot - graphviz version 2.38.0 (20140413.2041)

**Comment by nmandic78** [comment] 2020-10-04 13:29
Addendum:
Using graphviz functions, it works. So dot is doing its job and I'm even more inclined suspecting path formatting problem...

viz = dtreeviz(clf, X, y,
                target_name='target',
                feature_names=iris.feature_names,
                class_names=list(iris.target_names))

g = graphviz.Source(viz.dot, format='svg')
g.view()
g.render('tree2') # render and save SVG

**Comment by parrt** [comment] 2020-10-04 16:02
Yeah, it looks like `['dot', '-Tsvg', '-o', '/tmp/t.svg', '/tmp\t']` is doing `/tmp\t`,  which will be a problem.  thanks for letting us know!

**Comment by parrt** [comment] 2020-10-09 20:32
Ah. The example says to save as /tmp/t.svg, but that is simply a bad filename on Windows.  Given that I have to make the example work on at least one platform, I made it work on Windows and UNIX. So, this is not a bug in the software.  change that filename to `\temp\t.svg` or something from Windows and it should work.  please confirm

**Comment by nmandic78** [comment] 2020-10-10 15:39
Well, this is strange. It must be something I did, but I don't know what. 
Wish I would remember what packages I got updated in the meantime, but I don't. 
First thing: I got new exception when running your (unmodified) example; iris.py :

Exception has occurred: TypeError
can't multiply sequence by non-int of type 'float'
  File "C:\Users\User\source\repos\AdaBoost_testing_1a\DecisionTreeVisualization_1a\dtreeviz_test_github_1a\gh_test_1a.py", line 65, in <module>
    viz_iris().save("/tmp/t.svg")

But this is not a problem. In example, (.5,.5) is passed to scale argument, and scale_SVG(svg:str, scale:float) expects single float.
Strange thing is when this is corrected, it now works even with '/tmp/t.svg' path format. No more 'make sure the Graphviz executables are on your systems' PATH' exception. And I really didn't change anything... Same thing in my test scripts where I just uncommented code that previously raised the error.

Here is my complete short script (beside your iris example) just to avoid misinterpretation, :

`from matplotlib import pyplot as plt
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier 
from sklearn.tree import DecisionTreeRegressor
from sklearn import tree
import graphviz
from dtreeviz.trees import dtreeviz


# ************************************ CLASSIFIER ************************************
# Prepare the data data
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Fit the classifier with default hyper-parameters
clf = DecisionTreeClassifier(random_state=1234)
model = clf.fit(X, y)

print('clf: ', type(clf))

# Visualise as TEXT
text_representation = tree.export_text(clf)
print(text_representation)

# Visualise with matplotlib
fig = plt.figure(figsize=(15,10))
_ = tree.plot_tree(clf, 
                   feature_names=iris.feature_names,  
                   class_names=iris.target_names,
                   filled=True)

plt.show()
fig.savefig("decistion_tree.png")

# Visualise with graphviz
dot_data = tree.export_graphviz(clf, out_file=None, 
                                feature_names=iris.feature_names,  
                                class_names=iris.target_names,
                                filled=True)

graph = graphviz.Source(dot_data, format="png") 
graph.render("decision_tree_graphivz")
graph.view()

# Visualise with dtreeviz (best!)
# viz = dtreeviz(clf, X, y,
#                 target_name='target',
#                 feature_names=iris.feature_names,
#                 class_names=list(iris.target_names))

# g = graphviz.Source(viz.dot, format='svg')
# g.view()
# g.render('tree2') # render and save SVG

# This works now, but it didn't before :)
viz = dtreeviz(clf, X, y,
                target_name='target',
                feature_names=iris.feature_names,
                class_names=list(iris.target_names))

viz.save("/tmp/t.svg")
viz.view()`

File (t.svg) saved in C:\tmp\

I don't know..... Anyway, no problem anymore :)

Just one thing. Some imports in iris.py example are unnecessary and/or unavailable (_dtreeviz.shadow_ and  _fetch_mldata_ from sklearn.datasets).

I think we could close this one. If it happens again (or to someone else), easy to reinitiate.

Thank you for support and great lib (nicest one I found for tree visualization) 👍

**Comment by parrt** [comment] 2020-10-10 23:27
ok, closing since all seems to be well!  yeah, the examples are not super great and rigorously done.  Glad to be of service

**Closed by parrt** 2020-10-10 23:27 UTC
Labels: bug, compatibility
