### ISSUE TITLE
Cannot build tree: Method rawCount([]) does not exist

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [parrt/dtreeviz#104] opened 2020-09-27 18:18 UTC
I am trying to visualise a pyspark `DecisionTreeClassifier()` (for binary classification) and encountering an error: 

```
spark_tree  = ShadowSparkTree(MyPipelineModel.stages[2], X_dataset[regressors_features_list],
                              X_dataset["my_target"], feature_names= regressors_features_list,
                              target_name= "my_target", class_names=[0, 1])
trees.dtreeviz(spark_tree, fancy = True) 
```

Where the stage 2 of `MyPipelineModel` is an `DecisionTreeObject` object: 

```
MyDecisionTree = DecisionTreeClassifier(labelCol= "my_target", featuresCol="features", maxDepth=10, impurity= "gini")


```
where the `features` are the `regressors_features_list`, already assembled by a `VectorAssembler`.  

Here is the traceback that I'm getting after trying to run the first chunk: 

```
Py4JError                                 Traceback (most recent call last)
<ipython-input-21-234200c5628d> in <module>
----> 1 trees.dtreeviz(spark_tree, fancy=True)

~\Anaconda3\lib\site-packages\dtreeviz\trees.py in dtreeviz(tree_model, x_data, y_data, feature_names, target_name, class_names, tree_index, precision, orientation, instance_orientation, show_root_edge_labels, show_node_labels, show_just_path, fancy, histtype, highlight_path, X, max_X_features_LR, max_X_features_TD, label_fontsize, ticks_fontsize, fontname, colors, scale)
    822             class_leaf_viz(node, colors=color_values,
    823                            filename=f"{tmp}/leaf{node.id}_{os.getpid()}.svg",
--> 824                            graph_colors=colors)
    825             leaves.append(class_leaf_node(node))
    826         else:

~\Anaconda3\lib\site-packages\dtreeviz\trees.py in class_leaf_viz(node, colors, filename, graph_colors)
   1042     maxsize = 1.3
   1043     slope = 0.02
-> 1044     nsamples = node.nsamples()
   1045     size = nsamples * slope + minsize
   1046     size = min(size, maxsize)

~\Anaconda3\lib\site-packages\dtreeviz\models\shadow_decision_tree.py in nsamples(self)
    494         """
    495 
--> 496         return self.shadow_tree.get_node_nsamples(self.id)
    497 
    498     # TODO

~\Anaconda3\lib\site-packages\dtreeviz\models\spark_decision_tree.py in get_node_nsamples(self, id)
    124 
    125     def get_node_nsamples(self, id):
--> 126         return self.tree_nodes[id].impurityStats().rawCount()
    127 
    128     def get_children_left(self) -> np.ndarray:


Py4JError: An error occurred while calling o4374.rawCount. Trace:
py4j.Py4JException: Method rawCount([]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
```
(some strings referring to Py4j are elided, since they are senseless) 

Some of  `dtreeviz` methods work normally, e.g. `.ctreeviz_leaf_samples()` shows an intelligible graph (distribution of elements in leaves among classes).

Everything is being done on Jupyter Notebook with Python 3.7.4 Kernel (ased on conda). Dependencies are: `pandas`, `pyspark`, `dtreeviz`, `numpy`. 

The Spark version is 2.4.

Could somebody please help me and tell, maybe I'm doing something wrong or more information about the code is required?

Thanks beforehand for any assistance!

**Comment by tlapusan** [comment] 2020-09-28 09:54
hi @gjirokastrelbasanit34,

at first, it seems to be a spark version problem... when we added spark to dtreeviz, we worked on spark 3.0.0.
I will take a deeper look in the next days.

Until then, would be possible for you to upgrade to spark 3.0 and to see if the error persist ? (I assume your code should also work with spark 3.0)

**Comment by tlapusan** [comment] 2020-10-01 10:42
hi @gjirokastrelbasanit34,

I've checked both spark 2.4 and 3.0 APIs and the error is because of spark version. Spark 3.0 contains rawCount() method, but Spark 2.4 it doesn't. We will think how to solve this, because spark 2.4 is still used by a lot of people.

Until this is solved, would be an issue if you will upgrade to Spark 3.0 ?

Spark 3.0 API
  /**
   * Weighted number of data points accounted for in the sufficient statistics.
   */
  def count: Double

  /**
   * Raw number of data points accounted for in the sufficient statistics.
   */
  var rawCount: Long

Spark 2.4 API

  /**
   * Number of data points accounted for in the sufficient statistics.
   */
  def count: Long

**Comment by tlapusan** [comment] 2020-10-02 13:54
@gjirokastrelbasanit34 I've just created a PR for Spark 2 support.

@parrt can you check #107 PR and make a new release ? I assume majority of people are using Spark 2, since Spark 3 was released in the last months.

**Comment by parrt** [comment] 2020-10-02 18:09
Closed by https://github.com/parrt/dtreeviz/pull/107 right?

**Comment by tlapusan** [comment] 2020-10-02 18:49
> Closed by #107 right? I pushed 1.1.2 dtreeviz just now.

I would wait a little(1-2 days) after @gjirokastrelbasanit34 to test/confirm it.

**Comment by parrt** [comment] 2020-10-02 18:53
haha. too late. thought he'd checked it. we can do 1.1.3 if we need to fix. i didn't tweet anything

**Comment by gjirokastrelbasanit34** [comment] 2020-10-05 11:42
No, I haven't done/checked up anything until now, alas.
I just apologise for visiting GH not so frequently)

But fortunately, your suggestion works - on Spark 3.1, this error no longer emerges.
Switching versions itself is not a problem for me, I have been previously using Spark 2.4 version only due to an error (irrelevant to this issue) that I ran into when trying to launch Spark for the first time. But now that error seems to be gone, so I will just quit with Spark 2.4. 
 
However, another issue pops up immediately: 
I do have `graphviz` executable installed and added onto my System PATH (e.g. standalone `graphviz` package works decently), however, the same chunk  (`trees.dtreeviz(spark_tree, fancy = True)`)  regurgitates the `ExecutableNotFound` Error: 
```
ExecutableNotFound: failed to execute ['dot', '-Tsvg', '-o', 'C:\\Users\\username\\AppData\\Local\\Temp\\DTreeViz_5304.svg', 'C:/User/userna/AppData/Local/Temp\\DTreeViz_5304'], make sure the Graphviz executables are on your systems' PATH
```
But this is just a #109 bug already being on watchlist.

You have mentioned adding Spark 2 support in connection with this issue - should I just reinstall `dtreeviz` to test whether your improvement works for me (on Spark 2.4) or should I copy some code from certain files located on this repo and substitute any source code in `dtreeviz` files installed on my PC?

Thanks for the response in advance!

**Comment by tlapusan** [comment] 2020-10-05 18:25
hi @gjirokastrelbasanit34, would be nice if you can test for Spark 2.4.
You just need to install the newest dtreeviz version, 1.12.

I'm using mac...so would be hard to reproduce your issue unfortunately. I do remember I had graphviz issues in the beginning and I solved them by "pip install pygraphviz --install-option="--include-path=/usr/local/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/", but this command is not useful for you since you are using windows.
Do the other visualizations work ?

@parrt  do you have any idea how to solve this issue ?

**Comment by parrt** [comment] 2020-10-08 16:51
Sounds like dot issue is #109.

**Comment by gjirokastrelbasanit34** [comment] 2020-10-09 19:04
Hi @tlapusan , yes, all other visualisations work, but that is not a secret that the tree itself is the most valuable one. 
So far, looking forward to obtaining the bugfix for #109.

**Comment by parrt** [comment] 2020-10-09 20:33
@gjirokastrelbasanit34 #109 is not a bug.  User is sending a UNIX filename into dtreeviz on a Windows machine. Perhaps that is causing you issues here.

**Closed** 2020-11-25 21:01 UTC
