### ISSUE TITLE
IndexError: arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by munro** [parrt/dtreeviz#169] opened 2021-12-09 16:29 UTC
Sorry, I don't have code to reproduce this yet, but here's the stack trace I'm getting.  It seems to occur when I have shallower trees, or maybe not enough samples on a leaf?  Because `DecisionTreeRegressor(min_samples_leaf=20)` will make this error message go away.

```python
--------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_6281/129338585.py in <module>
----> 1 dtreeviz(
      2     dt,
      3     cast(Any, val_x).values,
      4     val_y,
      5     target_name="y",

~/miniconda3/envs/kwds/lib/python3.9/site-packages/dtreeviz/trees.py in dtreeviz(tree_model, x_data, y_data, feature_names, target_name, class_names, tree_index, precision, orientation, instance_orientation, show_root_edge_labels, show_node_labels, show_just_path, fancy, histtype, highlight_path, X, max_X_features_LR, max_X_features_TD, depth_range_to_display, label_fontsize, ticks_fontsize, fontname, title, title_fontsize, colors, scale)
    812                                 highlight_node=node.id in highlight_path)
    813             else:
--> 814                 regr_split_viz(node, X_data, y_data,
    815                                filename=f"{tmp}/node{node.id}_{os.getpid()}.svg",
    816                                target_name=shadow_tree.target_name,

~/miniconda3/envs/kwds/lib/python3.9/site-packages/dtreeviz/trees.py in regr_split_viz(node, X_train, y_train, target_name, filename, y_range, ticks_fontsize, label_fontsize, fontname, precision, X, highlight_node, colors)
   1163 
   1164         ax.scatter(X_feature, y_train, s=5, c=colors['scatter_marker'], alpha=colors['scatter_marker_alpha'], lw=.3)
-> 1165         left, right = node.split_samples()
   1166         left = y_train[left]
   1167         right = y_train[right]

~/miniconda3/envs/kwds/lib/python3.9/site-packages/dtreeviz/models/shadow_decision_tree.py in split_samples(self)
    559         """Returns the list of indexes to the left and the right of the split value."""
    560 
--> 561         return self.shadow_tree.get_split_samples(self.id)
    562 
    563     def isleaf(self) -> bool:

~/miniconda3/envs/kwds/lib/python3.9/site-packages/dtreeviz/models/sklearn_decision_trees.py in get_split_samples(self, id)
     67     def get_split_samples(self, id):
     68         samples = np.array(self.get_node_samples()[id])
---> 69         node_X_data = self.x_data[samples, self.get_node_feature(id)]
     70         split = self.get_node_split(id)
     71 

IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by kw-john-prior** [comment] 2021-12-09 16:30
I'm getting this error also.

**Comment by parrt** [comment] 2021-12-09 18:24
Hi. Weird.  somehow the samples must be coming back None or floats or something weird. Any chance we can get some code that reproduces the issue?

**Comment by tlapusan** [comment] 2021-12-10 09:49
Hi @munro, the 'samples' variable should contain the training set samples' indexes which can be found in a specific node (represented by id) from the tree.
node_X_data will extract only the samples from that specific node. The error happens when you want to extract those samples. It should be something wrong at 'sample' initialisation. 
If you can make some debug to see what the 'sample' contain, it should help to solve this issue.

**Comment by MartyMcPayne** [comment] 2022-03-13 13:26
Hi @tlapusan and @parrt, it's me again 😛 

I'm getting the same error (`IndexError: arrays used as indices must be of integer (or boolean) type`) when running dtreeviz():
`trees.dtreeviz(tree_model = shadowTree,
							orientation = "LR",
							depth_range_to_display = (0, 5),
							precision = 2,
							scale = 2)`

And the preceding variable declarations:
`df = data_input`
`df_X = df.drop("smcl", axis = 1)`
`df_y = df["smcl"]`
`model_names = list(df_X.columns)`
`model_input.get_booster().feature_names = model_names`
`shadowTree = ShadowXGBDTree(booster = model_input, 
                                tree_index = 0, 
                                x_data = df_X,
                                y_data = df_y,
                               	feature_names = model_names,
                                target_name = "smcl")`

@tlapusan comment from 2021, suggests to me that it is not a function problem per se (e.g. me declaring an argument wrong somewhere), but a problem with the format of my data?
Previously, `data_input` had a DateIndex, which I reset to a RangeIndex, because I thought the date format of the index was throwing the IndexError, but that didn't solve the error.

Am I getting the error because some of the variables in the dataframe can't be converted to integers (assuming dtreeviz is doing this) because they are small numbers? e.g. 0.000139

The dataframe only consists of float32 and float64, e.g:
![image](https://user-images.githubusercontent.com/36521027/158061244-2fecc05a-ebfd-4d29-950c-821916db7ad4.png)

**Comment by tlapusan** [comment] 2022-03-14 08:42
Hi @MartyMcPayne ,

The error is happening at line "node_X_data = self.x_data[samples, self.get_node_feature(id)]" from xgb_decision_tree.py module.

Something is weird how 'samples' variable is initialized, but hard for me to debug without an environment where I could reproduce it.

Could you put some print() to see the type and values of samples ?

Or, if you dataset/notebook is not confidential and you can send it to me, I could try to make debug to see from where is the issue. Thanks.

**Comment by MartyMcPayne** [comment] 2022-03-14 15:42
@tlapusan thanks Tudor that would be very helpful, I'm preparing the files/notebook and will send them to you later.

**Comment by tlapusan** [comment] 2022-03-16 07:30
Hi @MartyMcPayne, I received your files, I will start to look over them soon. Thanks.

**Comment by tlapusan** [comment] 2022-03-16 10:21
At a first glance, the max_depth=15 is way too large for a training set with ~320 samples. The tree will hardly overfit.
There are a lot of nodes, and event simple operations take long time.

Could you change the depth to 3, 4 for example ?

I reproduce the error, but have to spend more time to understand the root cause.

**Comment by MartyMcPayne** [comment] 2022-03-16 11:12
@tlapusan will let you know how changing model max_depth to 3 / 4 affects the script

**Comment by MartyMcPayne** [comment] 2022-03-16 14:49
model max_depth reduced to 3/4 from 15 shortens the computation time of dtreeviz(), but still reaches IndexError failure.

**Comment by tlapusan** [comment] 2022-03-16 15:27
cool, could you put this model into the shared drive folder ? It would be faster to run it.

**Comment by MartyMcPayne** [comment] 2022-03-16 15:48
done. also updated ipynb markdown notes with computation times

**Comment by MartyMcPayne** [comment] 2022-03-16 17:07
@tlapusan think I solved it. fitted the model with updated parameters, will update shared folder to show you what I did.

**Comment by MartyMcPayne** [comment] 2022-03-16 17:19
model now took 26 seconds to succeed instead of 58 minutes to fail.
By altering the model parameters, is this likely to change the accuracy of the model? Will check with old model to compare.

For anyone in the future reading this thread, I _think_ the IndexError and slow computation was because the model was too complex. The parameters I changed are:
`model.max_depth = 5 # shortened depth`
`model.tree_method = "hist" # hist method supposed to be quicker than "exact"`
`model.n_estimators = 150 # reduced estimators from 500 to 150`
`model.verbosity = 1 # so model only prints warnings.`

**Comment by parrt** [comment] 2022-03-17 00:48
Wow, great detective work, @MartyMcPayne !!  @tlapusan should we close?

**Comment by tlapusan** [comment] 2022-03-17 07:17
@MartyMcPayne I checked also with the smaller max_depth and its working. 
Regarding the accuracy of the model, it's gonna change, but for the better :) Having depth of 15 for a small dataset (±300 rows) it's way to big and it will overfit the model.

@parrt  I still want to spend some more time on the issue, maybe I will find out why we had it on the large max_depth.

**Comment by MartyMcPayne** [comment] 2022-03-17 07:22
Thanks @parrt!
Thanks @tlapusan for your help! I'll keep the shared folder active if you want to use that for debugging?

**Comment by MartyMcPayne** [comment] 2022-03-17 07:30
Great! No problem : )

**Comment by MartyMcPayne** [comment] 2022-03-17 07:46
> model max_depth reduced to 3/4 from 15 shortens the computation time of dtreeviz(), but still reaches IndexError failure.

So I reduced the max_depth of the model, but I didn't fit the model afterwards here. So I think the model didn't "do anything" with the new parameter.

Regarding the 1200 minute runtime comment, at that time I was referring to the function's argument `depth_range_to_display`. So effectively I was changing what `dtreeviz()` was going to do, but hadn't changed anything with the model.

**Comment by tlapusan** [comment] 2022-03-17 08:43
talking about that tree with depth=15.... it has 24063 of nodes, which is kind of impossible to have that large number of nodes when the training set is only 50 rows (the subsample).

I have to check why the tree has so many nodes, but it seems like a bad implementation from xgboost library.

The initial error is caused because dtreeviz wants to render a node (id=255) and based on our preprocessing, this node has 0 samples.

**Comment by MartyMcPayne** [comment] 2022-03-17 09:02
Right, the model was originally trained over a _huuuge_ dataset, spanning a continent (before I joined the project).
I am tasked with scripting a decision tree visualisation for a subset, a 1 km2 cell (the ~300 rows). I originally sent 50 over because I thought it'd run faster with less data (naive).

So, I guess means that to scale down the model, I need to refit it to make working with it much easier/quicker.

**Comment by tlapusan** [comment] 2022-03-17 11:46
I understand now :)

Ideally would be to use the same training set on which the model was fit. Otherwise there could be some imprecise visualisation.

**Comment by MartyMcPayne** [comment] 2022-03-17 19:10
Ahhhh. That makes sense, thanks for the tips Tudor!

**Comment by tlapusan** [comment] 2022-03-17 19:46
@MartyMcPayne glad to help :), you can delete the google drive folder

I will close the issue. Thanks for re-opening the discussion! It helps to improve the library ;)

**Closed** 2022-03-17 19:46 UTC

**Comment by parrt** [comment] 2022-03-18 18:09
Thanks for digging into this @tlapusan and @MartyMcPayne !

**Comment by simlmx** [comment] 2023-04-04 20:17
I also struggled with git trees and got the same error. I used `fancy=False` to work around the issue.
